{{- if and .Values.backendBuyers.enabled .Values.backendBuyers.ingress.enabled -}}
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: marketplace-backend-buyers
  labels:
    {{- include "marketplace.labels" . | nindent 4 }}
    app: {{ .Values.common.appLabel }}
    component: backend-buyers
  {{- with .Values.backendBuyers.ingress.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  {{- with .Values.backendBuyers.ingress.className }}
  ingressClassName: {{ . }}
  {{- end }}
  {{- if .Values.backendBuyers.ingress.tls }}
  tls:
    {{- range .Values.backendBuyers.ingress.tls }}
    - hosts:
        {{- range .hosts }}
        - {{ . | quote }}
        {{- end }}
      secretName: {{ .secretName }}
    {{- end }}
  {{- end }}
  rules:
    {{- range .Values.backendBuyers.ingress.hosts }}
    - host: {{ .host | quote }}
      http:
        paths:
          {{- range .paths }}
          - path: {{ .path }}
            {{- with .pathType }}
            pathType: {{ . }}
            {{- end }}
            backend:
              service:
                name: marketplace-backend-buyers
                port:
                  number: {{ $.Values.backendBuyers.service.port }}
          {{- end }}
    {{- end }}
{{- end }}
