# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

from . import customer_db_pb2 as customer__db__pb2

GRPC_GENERATED_VERSION = '1.78.1'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + ' but the generated code in customer_db_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class CustomerDbServiceStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.CreateBuyer = channel.unary_unary(
                '/marketplace.customerdb.v1.CustomerDbService/CreateBuyer',
                request_serializer=customer__db__pb2.CreateBuyerRequest.SerializeToString,
                response_deserializer=customer__db__pb2.CreateBuyerResponse.FromString,
                _registered_method=True)
        self.AuthenticateBuyer = channel.unary_unary(
                '/marketplace.customerdb.v1.CustomerDbService/AuthenticateBuyer',
                request_serializer=customer__db__pb2.AuthenticateBuyerRequest.SerializeToString,
                response_deserializer=customer__db__pb2.AuthenticateBuyerResponse.FromString,
                _registered_method=True)
        self.GetBuyer = channel.unary_unary(
                '/marketplace.customerdb.v1.CustomerDbService/GetBuyer',
                request_serializer=customer__db__pb2.GetBuyerRequest.SerializeToString,
                response_deserializer=customer__db__pb2.GetBuyerResponse.FromString,
                _registered_method=True)
        self.IncrementBuyerPurchases = channel.unary_unary(
                '/marketplace.customerdb.v1.CustomerDbService/IncrementBuyerPurchases',
                request_serializer=customer__db__pb2.IncrementBuyerPurchasesRequest.SerializeToString,
                response_deserializer=customer__db__pb2.IncrementBuyerPurchasesResponse.FromString,
                _registered_method=True)
        self.CreateSeller = channel.unary_unary(
                '/marketplace.customerdb.v1.CustomerDbService/CreateSeller',
                request_serializer=customer__db__pb2.CreateSellerRequest.SerializeToString,
                response_deserializer=customer__db__pb2.CreateSellerResponse.FromString,
                _registered_method=True)
        self.AuthenticateSeller = channel.unary_unary(
                '/marketplace.customerdb.v1.CustomerDbService/AuthenticateSeller',
                request_serializer=customer__db__pb2.AuthenticateSellerRequest.SerializeToString,
                response_deserializer=customer__db__pb2.AuthenticateSellerResponse.FromString,
                _registered_method=True)
        self.GetSeller = channel.unary_unary(
                '/marketplace.customerdb.v1.CustomerDbService/GetSeller',
                request_serializer=customer__db__pb2.GetSellerRequest.SerializeToString,
                response_deserializer=customer__db__pb2.GetSellerResponse.FromString,
                _registered_method=True)
        self.UpdateSellerFeedback = channel.unary_unary(
                '/marketplace.customerdb.v1.CustomerDbService/UpdateSellerFeedback',
                request_serializer=customer__db__pb2.UpdateSellerFeedbackRequest.SerializeToString,
                response_deserializer=customer__db__pb2.UpdateSellerFeedbackResponse.FromString,
                _registered_method=True)
        self.IncrementSellerItemsSold = channel.unary_unary(
                '/marketplace.customerdb.v1.CustomerDbService/IncrementSellerItemsSold',
                request_serializer=customer__db__pb2.IncrementSellerItemsSoldRequest.SerializeToString,
                response_deserializer=customer__db__pb2.IncrementSellerItemsSoldResponse.FromString,
                _registered_method=True)
        self.CreateBuyerSession = channel.unary_unary(
                '/marketplace.customerdb.v1.CustomerDbService/CreateBuyerSession',
                request_serializer=customer__db__pb2.CreateBuyerSessionRequest.SerializeToString,
                response_deserializer=customer__db__pb2.CreateBuyerSessionResponse.FromString,
                _registered_method=True)
        self.ValidateBuyerSession = channel.unary_unary(
                '/marketplace.customerdb.v1.CustomerDbService/ValidateBuyerSession',
                request_serializer=customer__db__pb2.ValidateBuyerSessionRequest.SerializeToString,
                response_deserializer=customer__db__pb2.ValidateBuyerSessionResponse.FromString,
                _registered_method=True)
        self.DeleteBuyerSession = channel.unary_unary(
                '/marketplace.customerdb.v1.CustomerDbService/DeleteBuyerSession',
                request_serializer=customer__db__pb2.DeleteBuyerSessionRequest.SerializeToString,
                response_deserializer=customer__db__pb2.DeleteBuyerSessionResponse.FromString,
                _registered_method=True)
        self.TouchBuyerSession = channel.unary_unary(
                '/marketplace.customerdb.v1.CustomerDbService/TouchBuyerSession',
                request_serializer=customer__db__pb2.TouchBuyerSessionRequest.SerializeToString,
                response_deserializer=customer__db__pb2.TouchBuyerSessionResponse.FromString,
                _registered_method=True)
        self.CleanupExpiredBuyerSessions = channel.unary_unary(
                '/marketplace.customerdb.v1.CustomerDbService/CleanupExpiredBuyerSessions',
                request_serializer=customer__db__pb2.CleanupExpiredBuyerSessionsRequest.SerializeToString,
                response_deserializer=customer__db__pb2.CleanupExpiredBuyerSessionsResponse.FromString,
                _registered_method=True)
        self.CleanupBuyerSession = channel.unary_unary(
                '/marketplace.customerdb.v1.CustomerDbService/CleanupBuyerSession',
                request_serializer=customer__db__pb2.CleanupBuyerSessionRequest.SerializeToString,
                response_deserializer=customer__db__pb2.CleanupBuyerSessionResponse.FromString,
                _registered_method=True)
        self.CreateSellerSession = channel.unary_unary(
                '/marketplace.customerdb.v1.CustomerDbService/CreateSellerSession',
                request_serializer=customer__db__pb2.CreateSellerSessionRequest.SerializeToString,
                response_deserializer=customer__db__pb2.CreateSellerSessionResponse.FromString,
                _registered_method=True)
        self.ValidateSellerSession = channel.unary_unary(
                '/marketplace.customerdb.v1.CustomerDbService/ValidateSellerSession',
                request_serializer=customer__db__pb2.ValidateSellerSessionRequest.SerializeToString,
                response_deserializer=customer__db__pb2.ValidateSellerSessionResponse.FromString,
                _registered_method=True)
        self.DeleteSellerSession = channel.unary_unary(
                '/marketplace.customerdb.v1.CustomerDbService/DeleteSellerSession',
                request_serializer=customer__db__pb2.DeleteSellerSessionRequest.SerializeToString,
                response_deserializer=customer__db__pb2.DeleteSellerSessionResponse.FromString,
                _registered_method=True)
        self.TouchSellerSession = channel.unary_unary(
                '/marketplace.customerdb.v1.CustomerDbService/TouchSellerSession',
                request_serializer=customer__db__pb2.TouchSellerSessionRequest.SerializeToString,
                response_deserializer=customer__db__pb2.TouchSellerSessionResponse.FromString,
                _registered_method=True)
        self.CleanupExpiredSellerSessions = channel.unary_unary(
                '/marketplace.customerdb.v1.CustomerDbService/CleanupExpiredSellerSessions',
                request_serializer=customer__db__pb2.CleanupExpiredSellerSessionsRequest.SerializeToString,
                response_deserializer=customer__db__pb2.CleanupExpiredSellerSessionsResponse.FromString,
                _registered_method=True)
        self.CleanupSellerSession = channel.unary_unary(
                '/marketplace.customerdb.v1.CustomerDbService/CleanupSellerSession',
                request_serializer=customer__db__pb2.CleanupSellerSessionRequest.SerializeToString,
                response_deserializer=customer__db__pb2.CleanupSellerSessionResponse.FromString,
                _registered_method=True)
        self.GetSessionCart = channel.unary_unary(
                '/marketplace.customerdb.v1.CustomerDbService/GetSessionCart',
                request_serializer=customer__db__pb2.GetSessionCartRequest.SerializeToString,
                response_deserializer=customer__db__pb2.GetSessionCartResponse.FromString,
                _registered_method=True)
        self.SetSessionCartItem = channel.unary_unary(
                '/marketplace.customerdb.v1.CustomerDbService/SetSessionCartItem',
                request_serializer=customer__db__pb2.SetSessionCartItemRequest.SerializeToString,
                response_deserializer=customer__db__pb2.SetSessionCartItemResponse.FromString,
                _registered_method=True)
        self.RemoveSessionCartItem = channel.unary_unary(
                '/marketplace.customerdb.v1.CustomerDbService/RemoveSessionCartItem',
                request_serializer=customer__db__pb2.RemoveSessionCartItemRequest.SerializeToString,
                response_deserializer=customer__db__pb2.RemoveSessionCartItemResponse.FromString,
                _registered_method=True)
        self.ClearSessionCart = channel.unary_unary(
                '/marketplace.customerdb.v1.CustomerDbService/ClearSessionCart',
                request_serializer=customer__db__pb2.ClearSessionCartRequest.SerializeToString,
                response_deserializer=customer__db__pb2.ClearSessionCartResponse.FromString,
                _registered_method=True)
        self.GetSavedCart = channel.unary_unary(
                '/marketplace.customerdb.v1.CustomerDbService/GetSavedCart',
                request_serializer=customer__db__pb2.GetSavedCartRequest.SerializeToString,
                response_deserializer=customer__db__pb2.GetSavedCartResponse.FromString,
                _registered_method=True)
        self.SaveCart = channel.unary_unary(
                '/marketplace.customerdb.v1.CustomerDbService/SaveCart',
                request_serializer=customer__db__pb2.SaveCartRequest.SerializeToString,
                response_deserializer=customer__db__pb2.SaveCartResponse.FromString,
                _registered_method=True)
        self.ClearSavedCart = channel.unary_unary(
                '/marketplace.customerdb.v1.CustomerDbService/ClearSavedCart',
                request_serializer=customer__db__pb2.ClearSavedCartRequest.SerializeToString,
                response_deserializer=customer__db__pb2.ClearSavedCartResponse.FromString,
                _registered_method=True)
        self.LoadSavedCart = channel.unary_unary(
                '/marketplace.customerdb.v1.CustomerDbService/LoadSavedCart',
                request_serializer=customer__db__pb2.LoadSavedCartRequest.SerializeToString,
                response_deserializer=customer__db__pb2.LoadSavedCartResponse.FromString,
                _registered_method=True)
        self.AddPurchase = channel.unary_unary(
                '/marketplace.customerdb.v1.CustomerDbService/AddPurchase',
                request_serializer=customer__db__pb2.AddPurchaseRequest.SerializeToString,
                response_deserializer=customer__db__pb2.AddPurchaseResponse.FromString,
                _registered_method=True)
        self.GetPurchaseHistory = channel.unary_unary(
                '/marketplace.customerdb.v1.CustomerDbService/GetPurchaseHistory',
                request_serializer=customer__db__pb2.GetPurchaseHistoryRequest.SerializeToString,
                response_deserializer=customer__db__pb2.GetPurchaseHistoryResponse.FromString,
                _registered_method=True)


class CustomerDbServiceServicer(object):
    """Missing associated documentation comment in .proto file."""

    def CreateBuyer(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def AuthenticateBuyer(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetBuyer(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def IncrementBuyerPurchases(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def CreateSeller(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def AuthenticateSeller(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetSeller(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def UpdateSellerFeedback(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def IncrementSellerItemsSold(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def CreateBuyerSession(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ValidateBuyerSession(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def DeleteBuyerSession(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def TouchBuyerSession(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def CleanupExpiredBuyerSessions(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def CleanupBuyerSession(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def CreateSellerSession(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ValidateSellerSession(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def DeleteSellerSession(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def TouchSellerSession(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def CleanupExpiredSellerSessions(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def CleanupSellerSession(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetSessionCart(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def SetSessionCartItem(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def RemoveSessionCartItem(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ClearSessionCart(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetSavedCart(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def SaveCart(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ClearSavedCart(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def LoadSavedCart(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def AddPurchase(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetPurchaseHistory(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_CustomerDbServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'CreateBuyer': grpc.unary_unary_rpc_method_handler(
                    servicer.CreateBuyer,
                    request_deserializer=customer__db__pb2.CreateBuyerRequest.FromString,
                    response_serializer=customer__db__pb2.CreateBuyerResponse.SerializeToString,
            ),
            'AuthenticateBuyer': grpc.unary_unary_rpc_method_handler(
                    servicer.AuthenticateBuyer,
                    request_deserializer=customer__db__pb2.AuthenticateBuyerRequest.FromString,
                    response_serializer=customer__db__pb2.AuthenticateBuyerResponse.SerializeToString,
            ),
            'GetBuyer': grpc.unary_unary_rpc_method_handler(
                    servicer.GetBuyer,
                    request_deserializer=customer__db__pb2.GetBuyerRequest.FromString,
                    response_serializer=customer__db__pb2.GetBuyerResponse.SerializeToString,
            ),
            'IncrementBuyerPurchases': grpc.unary_unary_rpc_method_handler(
                    servicer.IncrementBuyerPurchases,
                    request_deserializer=customer__db__pb2.IncrementBuyerPurchasesRequest.FromString,
                    response_serializer=customer__db__pb2.IncrementBuyerPurchasesResponse.SerializeToString,
            ),
            'CreateSeller': grpc.unary_unary_rpc_method_handler(
                    servicer.CreateSeller,
                    request_deserializer=customer__db__pb2.CreateSellerRequest.FromString,
                    response_serializer=customer__db__pb2.CreateSellerResponse.SerializeToString,
            ),
            'AuthenticateSeller': grpc.unary_unary_rpc_method_handler(
                    servicer.AuthenticateSeller,
                    request_deserializer=customer__db__pb2.AuthenticateSellerRequest.FromString,
                    response_serializer=customer__db__pb2.AuthenticateSellerResponse.SerializeToString,
            ),
            'GetSeller': grpc.unary_unary_rpc_method_handler(
                    servicer.GetSeller,
                    request_deserializer=customer__db__pb2.GetSellerRequest.FromString,
                    response_serializer=customer__db__pb2.GetSellerResponse.SerializeToString,
            ),
            'UpdateSellerFeedback': grpc.unary_unary_rpc_method_handler(
                    servicer.UpdateSellerFeedback,
                    request_deserializer=customer__db__pb2.UpdateSellerFeedbackRequest.FromString,
                    response_serializer=customer__db__pb2.UpdateSellerFeedbackResponse.SerializeToString,
            ),
            'IncrementSellerItemsSold': grpc.unary_unary_rpc_method_handler(
                    servicer.IncrementSellerItemsSold,
                    request_deserializer=customer__db__pb2.IncrementSellerItemsSoldRequest.FromString,
                    response_serializer=customer__db__pb2.IncrementSellerItemsSoldResponse.SerializeToString,
            ),
            'CreateBuyerSession': grpc.unary_unary_rpc_method_handler(
                    servicer.CreateBuyerSession,
                    request_deserializer=customer__db__pb2.CreateBuyerSessionRequest.FromString,
                    response_serializer=customer__db__pb2.CreateBuyerSessionResponse.SerializeToString,
            ),
            'ValidateBuyerSession': grpc.unary_unary_rpc_method_handler(
                    servicer.ValidateBuyerSession,
                    request_deserializer=customer__db__pb2.ValidateBuyerSessionRequest.FromString,
                    response_serializer=customer__db__pb2.ValidateBuyerSessionResponse.SerializeToString,
            ),
            'DeleteBuyerSession': grpc.unary_unary_rpc_method_handler(
                    servicer.DeleteBuyerSession,
                    request_deserializer=customer__db__pb2.DeleteBuyerSessionRequest.FromString,
                    response_serializer=customer__db__pb2.DeleteBuyerSessionResponse.SerializeToString,
            ),
            'TouchBuyerSession': grpc.unary_unary_rpc_method_handler(
                    servicer.TouchBuyerSession,
                    request_deserializer=customer__db__pb2.TouchBuyerSessionRequest.FromString,
                    response_serializer=customer__db__pb2.TouchBuyerSessionResponse.SerializeToString,
            ),
            'CleanupExpiredBuyerSessions': grpc.unary_unary_rpc_method_handler(
                    servicer.CleanupExpiredBuyerSessions,
                    request_deserializer=customer__db__pb2.CleanupExpiredBuyerSessionsRequest.FromString,
                    response_serializer=customer__db__pb2.CleanupExpiredBuyerSessionsResponse.SerializeToString,
            ),
            'CleanupBuyerSession': grpc.unary_unary_rpc_method_handler(
                    servicer.CleanupBuyerSession,
                    request_deserializer=customer__db__pb2.CleanupBuyerSessionRequest.FromString,
                    response_serializer=customer__db__pb2.CleanupBuyerSessionResponse.SerializeToString,
            ),
            'CreateSellerSession': grpc.unary_unary_rpc_method_handler(
                    servicer.CreateSellerSession,
                    request_deserializer=customer__db__pb2.CreateSellerSessionRequest.FromString,
                    response_serializer=customer__db__pb2.CreateSellerSessionResponse.SerializeToString,
            ),
            'ValidateSellerSession': grpc.unary_unary_rpc_method_handler(
                    servicer.ValidateSellerSession,
                    request_deserializer=customer__db__pb2.ValidateSellerSessionRequest.FromString,
                    response_serializer=customer__db__pb2.ValidateSellerSessionResponse.SerializeToString,
            ),
            'DeleteSellerSession': grpc.unary_unary_rpc_method_handler(
                    servicer.DeleteSellerSession,
                    request_deserializer=customer__db__pb2.DeleteSellerSessionRequest.FromString,
                    response_serializer=customer__db__pb2.DeleteSellerSessionResponse.SerializeToString,
            ),
            'TouchSellerSession': grpc.unary_unary_rpc_method_handler(
                    servicer.TouchSellerSession,
                    request_deserializer=customer__db__pb2.TouchSellerSessionRequest.FromString,
                    response_serializer=customer__db__pb2.TouchSellerSessionResponse.SerializeToString,
            ),
            'CleanupExpiredSellerSessions': grpc.unary_unary_rpc_method_handler(
                    servicer.CleanupExpiredSellerSessions,
                    request_deserializer=customer__db__pb2.CleanupExpiredSellerSessionsRequest.FromString,
                    response_serializer=customer__db__pb2.CleanupExpiredSellerSessionsResponse.SerializeToString,
            ),
            'CleanupSellerSession': grpc.unary_unary_rpc_method_handler(
                    servicer.CleanupSellerSession,
                    request_deserializer=customer__db__pb2.CleanupSellerSessionRequest.FromString,
                    response_serializer=customer__db__pb2.CleanupSellerSessionResponse.SerializeToString,
            ),
            'GetSessionCart': grpc.unary_unary_rpc_method_handler(
                    servicer.GetSessionCart,
                    request_deserializer=customer__db__pb2.GetSessionCartRequest.FromString,
                    response_serializer=customer__db__pb2.GetSessionCartResponse.SerializeToString,
            ),
            'SetSessionCartItem': grpc.unary_unary_rpc_method_handler(
                    servicer.SetSessionCartItem,
                    request_deserializer=customer__db__pb2.SetSessionCartItemRequest.FromString,
                    response_serializer=customer__db__pb2.SetSessionCartItemResponse.SerializeToString,
            ),
            'RemoveSessionCartItem': grpc.unary_unary_rpc_method_handler(
                    servicer.RemoveSessionCartItem,
                    request_deserializer=customer__db__pb2.RemoveSessionCartItemRequest.FromString,
                    response_serializer=customer__db__pb2.RemoveSessionCartItemResponse.SerializeToString,
            ),
            'ClearSessionCart': grpc.unary_unary_rpc_method_handler(
                    servicer.ClearSessionCart,
                    request_deserializer=customer__db__pb2.ClearSessionCartRequest.FromString,
                    response_serializer=customer__db__pb2.ClearSessionCartResponse.SerializeToString,
            ),
            'GetSavedCart': grpc.unary_unary_rpc_method_handler(
                    servicer.GetSavedCart,
                    request_deserializer=customer__db__pb2.GetSavedCartRequest.FromString,
                    response_serializer=customer__db__pb2.GetSavedCartResponse.SerializeToString,
            ),
            'SaveCart': grpc.unary_unary_rpc_method_handler(
                    servicer.SaveCart,
                    request_deserializer=customer__db__pb2.SaveCartRequest.FromString,
                    response_serializer=customer__db__pb2.SaveCartResponse.SerializeToString,
            ),
            'ClearSavedCart': grpc.unary_unary_rpc_method_handler(
                    servicer.ClearSavedCart,
                    request_deserializer=customer__db__pb2.ClearSavedCartRequest.FromString,
                    response_serializer=customer__db__pb2.ClearSavedCartResponse.SerializeToString,
            ),
            'LoadSavedCart': grpc.unary_unary_rpc_method_handler(
                    servicer.LoadSavedCart,
                    request_deserializer=customer__db__pb2.LoadSavedCartRequest.FromString,
                    response_serializer=customer__db__pb2.LoadSavedCartResponse.SerializeToString,
            ),
            'AddPurchase': grpc.unary_unary_rpc_method_handler(
                    servicer.AddPurchase,
                    request_deserializer=customer__db__pb2.AddPurchaseRequest.FromString,
                    response_serializer=customer__db__pb2.AddPurchaseResponse.SerializeToString,
            ),
            'GetPurchaseHistory': grpc.unary_unary_rpc_method_handler(
                    servicer.GetPurchaseHistory,
                    request_deserializer=customer__db__pb2.GetPurchaseHistoryRequest.FromString,
                    response_serializer=customer__db__pb2.GetPurchaseHistoryResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'marketplace.customerdb.v1.CustomerDbService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('marketplace.customerdb.v1.CustomerDbService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class CustomerDbService(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def CreateBuyer(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/marketplace.customerdb.v1.CustomerDbService/CreateBuyer',
            customer__db__pb2.CreateBuyerRequest.SerializeToString,
            customer__db__pb2.CreateBuyerResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def AuthenticateBuyer(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/marketplace.customerdb.v1.CustomerDbService/AuthenticateBuyer',
            customer__db__pb2.AuthenticateBuyerRequest.SerializeToString,
            customer__db__pb2.AuthenticateBuyerResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetBuyer(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/marketplace.customerdb.v1.CustomerDbService/GetBuyer',
            customer__db__pb2.GetBuyerRequest.SerializeToString,
            customer__db__pb2.GetBuyerResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def IncrementBuyerPurchases(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/marketplace.customerdb.v1.CustomerDbService/IncrementBuyerPurchases',
            customer__db__pb2.IncrementBuyerPurchasesRequest.SerializeToString,
            customer__db__pb2.IncrementBuyerPurchasesResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def CreateSeller(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/marketplace.customerdb.v1.CustomerDbService/CreateSeller',
            customer__db__pb2.CreateSellerRequest.SerializeToString,
            customer__db__pb2.CreateSellerResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def AuthenticateSeller(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/marketplace.customerdb.v1.CustomerDbService/AuthenticateSeller',
            customer__db__pb2.AuthenticateSellerRequest.SerializeToString,
            customer__db__pb2.AuthenticateSellerResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetSeller(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/marketplace.customerdb.v1.CustomerDbService/GetSeller',
            customer__db__pb2.GetSellerRequest.SerializeToString,
            customer__db__pb2.GetSellerResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def UpdateSellerFeedback(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/marketplace.customerdb.v1.CustomerDbService/UpdateSellerFeedback',
            customer__db__pb2.UpdateSellerFeedbackRequest.SerializeToString,
            customer__db__pb2.UpdateSellerFeedbackResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def IncrementSellerItemsSold(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/marketplace.customerdb.v1.CustomerDbService/IncrementSellerItemsSold',
            customer__db__pb2.IncrementSellerItemsSoldRequest.SerializeToString,
            customer__db__pb2.IncrementSellerItemsSoldResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def CreateBuyerSession(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/marketplace.customerdb.v1.CustomerDbService/CreateBuyerSession',
            customer__db__pb2.CreateBuyerSessionRequest.SerializeToString,
            customer__db__pb2.CreateBuyerSessionResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ValidateBuyerSession(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/marketplace.customerdb.v1.CustomerDbService/ValidateBuyerSession',
            customer__db__pb2.ValidateBuyerSessionRequest.SerializeToString,
            customer__db__pb2.ValidateBuyerSessionResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def DeleteBuyerSession(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/marketplace.customerdb.v1.CustomerDbService/DeleteBuyerSession',
            customer__db__pb2.DeleteBuyerSessionRequest.SerializeToString,
            customer__db__pb2.DeleteBuyerSessionResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def TouchBuyerSession(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/marketplace.customerdb.v1.CustomerDbService/TouchBuyerSession',
            customer__db__pb2.TouchBuyerSessionRequest.SerializeToString,
            customer__db__pb2.TouchBuyerSessionResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def CleanupExpiredBuyerSessions(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/marketplace.customerdb.v1.CustomerDbService/CleanupExpiredBuyerSessions',
            customer__db__pb2.CleanupExpiredBuyerSessionsRequest.SerializeToString,
            customer__db__pb2.CleanupExpiredBuyerSessionsResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def CleanupBuyerSession(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/marketplace.customerdb.v1.CustomerDbService/CleanupBuyerSession',
            customer__db__pb2.CleanupBuyerSessionRequest.SerializeToString,
            customer__db__pb2.CleanupBuyerSessionResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def CreateSellerSession(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/marketplace.customerdb.v1.CustomerDbService/CreateSellerSession',
            customer__db__pb2.CreateSellerSessionRequest.SerializeToString,
            customer__db__pb2.CreateSellerSessionResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ValidateSellerSession(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/marketplace.customerdb.v1.CustomerDbService/ValidateSellerSession',
            customer__db__pb2.ValidateSellerSessionRequest.SerializeToString,
            customer__db__pb2.ValidateSellerSessionResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def DeleteSellerSession(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/marketplace.customerdb.v1.CustomerDbService/DeleteSellerSession',
            customer__db__pb2.DeleteSellerSessionRequest.SerializeToString,
            customer__db__pb2.DeleteSellerSessionResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def TouchSellerSession(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/marketplace.customerdb.v1.CustomerDbService/TouchSellerSession',
            customer__db__pb2.TouchSellerSessionRequest.SerializeToString,
            customer__db__pb2.TouchSellerSessionResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def CleanupExpiredSellerSessions(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/marketplace.customerdb.v1.CustomerDbService/CleanupExpiredSellerSessions',
            customer__db__pb2.CleanupExpiredSellerSessionsRequest.SerializeToString,
            customer__db__pb2.CleanupExpiredSellerSessionsResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def CleanupSellerSession(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/marketplace.customerdb.v1.CustomerDbService/CleanupSellerSession',
            customer__db__pb2.CleanupSellerSessionRequest.SerializeToString,
            customer__db__pb2.CleanupSellerSessionResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetSessionCart(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/marketplace.customerdb.v1.CustomerDbService/GetSessionCart',
            customer__db__pb2.GetSessionCartRequest.SerializeToString,
            customer__db__pb2.GetSessionCartResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def SetSessionCartItem(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/marketplace.customerdb.v1.CustomerDbService/SetSessionCartItem',
            customer__db__pb2.SetSessionCartItemRequest.SerializeToString,
            customer__db__pb2.SetSessionCartItemResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def RemoveSessionCartItem(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/marketplace.customerdb.v1.CustomerDbService/RemoveSessionCartItem',
            customer__db__pb2.RemoveSessionCartItemRequest.SerializeToString,
            customer__db__pb2.RemoveSessionCartItemResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ClearSessionCart(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/marketplace.customerdb.v1.CustomerDbService/ClearSessionCart',
            customer__db__pb2.ClearSessionCartRequest.SerializeToString,
            customer__db__pb2.ClearSessionCartResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetSavedCart(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/marketplace.customerdb.v1.CustomerDbService/GetSavedCart',
            customer__db__pb2.GetSavedCartRequest.SerializeToString,
            customer__db__pb2.GetSavedCartResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def SaveCart(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/marketplace.customerdb.v1.CustomerDbService/SaveCart',
            customer__db__pb2.SaveCartRequest.SerializeToString,
            customer__db__pb2.SaveCartResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ClearSavedCart(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/marketplace.customerdb.v1.CustomerDbService/ClearSavedCart',
            customer__db__pb2.ClearSavedCartRequest.SerializeToString,
            customer__db__pb2.ClearSavedCartResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def LoadSavedCart(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/marketplace.customerdb.v1.CustomerDbService/LoadSavedCart',
            customer__db__pb2.LoadSavedCartRequest.SerializeToString,
            customer__db__pb2.LoadSavedCartResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def AddPurchase(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/marketplace.customerdb.v1.CustomerDbService/AddPurchase',
            customer__db__pb2.AddPurchaseRequest.SerializeToString,
            customer__db__pb2.AddPurchaseResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetPurchaseHistory(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/marketplace.customerdb.v1.CustomerDbService/GetPurchaseHistory',
            customer__db__pb2.GetPurchaseHistoryRequest.SerializeToString,
            customer__db__pb2.GetPurchaseHistoryResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
