# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

from . import product_db_pb2 as product__db__pb2

GRPC_GENERATED_VERSION = '1.78.1'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + ' but the generated code in product_db_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class ProductDbServiceStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.CreateItem = channel.unary_unary(
                '/marketplace.productdb.v1.ProductDbService/CreateItem',
                request_serializer=product__db__pb2.CreateItemRequest.SerializeToString,
                response_deserializer=product__db__pb2.CreateItemResponse.FromString,
                _registered_method=True)
        self.GetItem = channel.unary_unary(
                '/marketplace.productdb.v1.ProductDbService/GetItem',
                request_serializer=product__db__pb2.GetItemRequest.SerializeToString,
                response_deserializer=product__db__pb2.GetItemResponse.FromString,
                _registered_method=True)
        self.UpdateItemPrice = channel.unary_unary(
                '/marketplace.productdb.v1.ProductDbService/UpdateItemPrice',
                request_serializer=product__db__pb2.UpdateItemPriceRequest.SerializeToString,
                response_deserializer=product__db__pb2.UpdateItemPriceResponse.FromString,
                _registered_method=True)
        self.UpdateItemQuantity = channel.unary_unary(
                '/marketplace.productdb.v1.ProductDbService/UpdateItemQuantity',
                request_serializer=product__db__pb2.UpdateItemQuantityRequest.SerializeToString,
                response_deserializer=product__db__pb2.UpdateItemQuantityResponse.FromString,
                _registered_method=True)
        self.DeleteItem = channel.unary_unary(
                '/marketplace.productdb.v1.ProductDbService/DeleteItem',
                request_serializer=product__db__pb2.DeleteItemRequest.SerializeToString,
                response_deserializer=product__db__pb2.DeleteItemResponse.FromString,
                _registered_method=True)
        self.ListItemsBySeller = channel.unary_unary(
                '/marketplace.productdb.v1.ProductDbService/ListItemsBySeller',
                request_serializer=product__db__pb2.ListItemsBySellerRequest.SerializeToString,
                response_deserializer=product__db__pb2.ListItemsBySellerResponse.FromString,
                _registered_method=True)
        self.SearchItems = channel.unary_unary(
                '/marketplace.productdb.v1.ProductDbService/SearchItems',
                request_serializer=product__db__pb2.SearchItemsRequest.SerializeToString,
                response_deserializer=product__db__pb2.SearchItemsResponse.FromString,
                _registered_method=True)
        self.AddFeedbackVote = channel.unary_unary(
                '/marketplace.productdb.v1.ProductDbService/AddFeedbackVote',
                request_serializer=product__db__pb2.AddFeedbackVoteRequest.SerializeToString,
                response_deserializer=product__db__pb2.AddFeedbackVoteResponse.FromString,
                _registered_method=True)
        self.GetItemFeedback = channel.unary_unary(
                '/marketplace.productdb.v1.ProductDbService/GetItemFeedback',
                request_serializer=product__db__pb2.GetItemFeedbackRequest.SerializeToString,
                response_deserializer=product__db__pb2.GetItemFeedbackResponse.FromString,
                _registered_method=True)
        self.CheckBuyerVoted = channel.unary_unary(
                '/marketplace.productdb.v1.ProductDbService/CheckBuyerVoted',
                request_serializer=product__db__pb2.CheckBuyerVotedRequest.SerializeToString,
                response_deserializer=product__db__pb2.CheckBuyerVotedResponse.FromString,
                _registered_method=True)


class ProductDbServiceServicer(object):
    """Missing associated documentation comment in .proto file."""

    def CreateItem(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetItem(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def UpdateItemPrice(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def UpdateItemQuantity(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def DeleteItem(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ListItemsBySeller(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def SearchItems(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def AddFeedbackVote(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetItemFeedback(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def CheckBuyerVoted(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_ProductDbServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'CreateItem': grpc.unary_unary_rpc_method_handler(
                    servicer.CreateItem,
                    request_deserializer=product__db__pb2.CreateItemRequest.FromString,
                    response_serializer=product__db__pb2.CreateItemResponse.SerializeToString,
            ),
            'GetItem': grpc.unary_unary_rpc_method_handler(
                    servicer.GetItem,
                    request_deserializer=product__db__pb2.GetItemRequest.FromString,
                    response_serializer=product__db__pb2.GetItemResponse.SerializeToString,
            ),
            'UpdateItemPrice': grpc.unary_unary_rpc_method_handler(
                    servicer.UpdateItemPrice,
                    request_deserializer=product__db__pb2.UpdateItemPriceRequest.FromString,
                    response_serializer=product__db__pb2.UpdateItemPriceResponse.SerializeToString,
            ),
            'UpdateItemQuantity': grpc.unary_unary_rpc_method_handler(
                    servicer.UpdateItemQuantity,
                    request_deserializer=product__db__pb2.UpdateItemQuantityRequest.FromString,
                    response_serializer=product__db__pb2.UpdateItemQuantityResponse.SerializeToString,
            ),
            'DeleteItem': grpc.unary_unary_rpc_method_handler(
                    servicer.DeleteItem,
                    request_deserializer=product__db__pb2.DeleteItemRequest.FromString,
                    response_serializer=product__db__pb2.DeleteItemResponse.SerializeToString,
            ),
            'ListItemsBySeller': grpc.unary_unary_rpc_method_handler(
                    servicer.ListItemsBySeller,
                    request_deserializer=product__db__pb2.ListItemsBySellerRequest.FromString,
                    response_serializer=product__db__pb2.ListItemsBySellerResponse.SerializeToString,
            ),
            'SearchItems': grpc.unary_unary_rpc_method_handler(
                    servicer.SearchItems,
                    request_deserializer=product__db__pb2.SearchItemsRequest.FromString,
                    response_serializer=product__db__pb2.SearchItemsResponse.SerializeToString,
            ),
            'AddFeedbackVote': grpc.unary_unary_rpc_method_handler(
                    servicer.AddFeedbackVote,
                    request_deserializer=product__db__pb2.AddFeedbackVoteRequest.FromString,
                    response_serializer=product__db__pb2.AddFeedbackVoteResponse.SerializeToString,
            ),
            'GetItemFeedback': grpc.unary_unary_rpc_method_handler(
                    servicer.GetItemFeedback,
                    request_deserializer=product__db__pb2.GetItemFeedbackRequest.FromString,
                    response_serializer=product__db__pb2.GetItemFeedbackResponse.SerializeToString,
            ),
            'CheckBuyerVoted': grpc.unary_unary_rpc_method_handler(
                    servicer.CheckBuyerVoted,
                    request_deserializer=product__db__pb2.CheckBuyerVotedRequest.FromString,
                    response_serializer=product__db__pb2.CheckBuyerVotedResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'marketplace.productdb.v1.ProductDbService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('marketplace.productdb.v1.ProductDbService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class ProductDbService(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def CreateItem(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/marketplace.productdb.v1.ProductDbService/CreateItem',
            product__db__pb2.CreateItemRequest.SerializeToString,
            product__db__pb2.CreateItemResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetItem(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/marketplace.productdb.v1.ProductDbService/GetItem',
            product__db__pb2.GetItemRequest.SerializeToString,
            product__db__pb2.GetItemResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def UpdateItemPrice(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/marketplace.productdb.v1.ProductDbService/UpdateItemPrice',
            product__db__pb2.UpdateItemPriceRequest.SerializeToString,
            product__db__pb2.UpdateItemPriceResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def UpdateItemQuantity(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/marketplace.productdb.v1.ProductDbService/UpdateItemQuantity',
            product__db__pb2.UpdateItemQuantityRequest.SerializeToString,
            product__db__pb2.UpdateItemQuantityResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def DeleteItem(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/marketplace.productdb.v1.ProductDbService/DeleteItem',
            product__db__pb2.DeleteItemRequest.SerializeToString,
            product__db__pb2.DeleteItemResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ListItemsBySeller(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/marketplace.productdb.v1.ProductDbService/ListItemsBySeller',
            product__db__pb2.ListItemsBySellerRequest.SerializeToString,
            product__db__pb2.ListItemsBySellerResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def SearchItems(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/marketplace.productdb.v1.ProductDbService/SearchItems',
            product__db__pb2.SearchItemsRequest.SerializeToString,
            product__db__pb2.SearchItemsResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def AddFeedbackVote(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/marketplace.productdb.v1.ProductDbService/AddFeedbackVote',
            product__db__pb2.AddFeedbackVoteRequest.SerializeToString,
            product__db__pb2.AddFeedbackVoteResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetItemFeedback(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/marketplace.productdb.v1.ProductDbService/GetItemFeedback',
            product__db__pb2.GetItemFeedbackRequest.SerializeToString,
            product__db__pb2.GetItemFeedbackResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def CheckBuyerVoted(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/marketplace.productdb.v1.ProductDbService/CheckBuyerVoted',
            product__db__pb2.CheckBuyerVotedRequest.SerializeToString,
            product__db__pb2.CheckBuyerVotedResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
